sudo: false
cache: bundler
rvm:
  - 2.5.0
  - 2.6.0
addons:
  chrome: stable
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
env:
  global:
    - TRAVIS=true
    - DISPLAY=:99.0
    - TEASPOON_DEVELOPMENT=true
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g istanbul
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - gem install bundler
script:
  - bundle exec rake
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter format-coverage -t simplecov -o ./coverage/codeclimate.json ./coverage/.resultset.json; fi
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage -i ./coverage/codeclimate.json; fi
